name: japanese_text_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - jupyterlab
  - ipywidgets
  - pandas
  - umap-learn
  - hdbscan
  - gensim
  - jieba
  - cairosvg
  - tabulate
  - elasticsearch
  - pip
  - pip:
    - defopt
    - dash
    - dash-core-components
    - dash-html-components
    - dash-renderer
    - dash-table
    - plotly-express
    - zhon
    - segtok
    - Cihai
    - logzero
